FROM node:22-alpine AS build
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN yarn install --immutable
RUN yarn workspace app build

FROM nginx:alpine-slim
RUN apk update && apk add jq && rm -rf /var/lib/apk/lists/*
COPY --from=build /app/packages/app/dist /usr/share/nginx/html
COPY container-config/default.conf.template /etc/nginx/templates/default.conf.template
COPY container-config/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
ENV PORT=80