name: ci
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches: [main]
jobs:
  build-and-test-containers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: docker build and run
        run: |
          docker image build -t backend:local .
          docker run -d \
              -u 65532 \
              --cap-drop=ALL \
              --read-only \
              --tmpfs /tmp \
              -e APP_CONFIG_backend_database_client='better-sqlite3' \
              -e APP_CONFIG_backend_database_connection=':memory:' \
              -e APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment='true' \
              -p 7007:7007 \
              backend:local
          sleep 10
          docker image build -f Dockerfile.frontend -t frontend:local .
          docker run -d \
              -e APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment='true' \
              -p 3000:3000 \
              frontend:local
          curl localhost:3000
          
