name: ci
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-and-test-containers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: make compose-test
        run: |
          docker image build -t backstage:local .
          docker run -d \
              -e APP_CONFIG_backend_database_client='better-sqlite3' \
              -e APP_CONFIG_backend_database_connection=':memory:' \
              -e APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment='true' \
              -p 7007:7007 \
              backstage:local
          sleep 10
          curl localhost:7007
          